sudo: false
language: node_js
node_js:
  - '6'
  - '7'
  - '8'
install:
  - npm i codecov lerna && ./node_modules/.bin/lerna bootstrap
script:
  - npm run ci
after_script:
  - ./node_modules/.bin/codecov
