sudo: false
git:
  depth: 10
language: node_js
node_js:
  - '6'
  - '8'
  - '9'
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - yarn run install-ci
  - yarn global add codecov
script:
  - yarn run ci
after_script:
  - codecov
